name: 'Kotangent'
url: 'briankoser.com'
author: 'Brian Koser'

subheading: 'Brian Koserâ€™s Blog'
timezone: 'America/Chicago'

permalink: '/blog/:title/'
paginate: 10
paginate_path: '/blog/page:num/'

exclude: ['Kotangent.sln', 'Kotangent.v11.suo', 'LICENSE.txt', 'Rakefile', 'README.md']

markdown: 'redcarpet'

pygments: false